"""Report export endpoints.

Reports are generated exclusively from the stored scan snapshot — never by
rescanning the target. The scan ID is validated against a strict pattern
before it is used in any output filename, so malformed or malicious
identifiers cannot influence filesystem behavior.
"""

import logging
import re

from fastapi import APIRouter, HTTPException, Response

from app.services import history_service, reporting_service

logger = logging.getLogger("cybershield.reports")

router = APIRouter(prefix="/reports", tags=["reports"])

# Scan IDs are generated by the backend (CS-YYYY-XXXXXXXX) and persisted;
# any other shape is rejected rather than echoed into filenames.
_SAFE_SCAN_ID = re.compile(r"^[A-Za-z0-9-]{1,64}$")


@router.get("/{scan_id}/{fmt}")
def export_report(scan_id: str, fmt: str) -> Response:
    if not _SAFE_SCAN_ID.fullmatch(scan_id):
        raise HTTPException(status_code=404, detail="Scan not found.")
    if fmt not in reporting_service.MEDIA_TYPES:
        raise HTTPException(status_code=422, detail=f"Unsupported format '{fmt}'.")

    analysis = history_service.get_scan(scan_id)
    if analysis is None:
        raise HTTPException(status_code=404, detail="Scan not found.")

    try:
        report = reporting_service.generate_report(analysis, fmt)
    except reporting_service.UnsupportedFormatError:
        raise HTTPException(status_code=422, detail=f"Unsupported format '{fmt}'.") from None
    except Exception:  # noqa: BLE001 - never leak exporter internals
        logger.exception("Report export failed for scan %s (%s)", scan_id, fmt)
        raise HTTPException(
            status_code=500,
            detail="The report could not be generated.",
        ) from None

    return Response(
        content=report.content,
        media_type=report.media_type,
        headers={
            "Content-Disposition": f'attachment; filename="{report.filename}"',
            "X-Content-Type-Options": "nosniff",
            "Cache-Control": "no-store",
        },
    )
